import os
import time
from typing import List, Any, Tuple, Set, Dict

import random

from fuzzer.fuzzer import Fuzzer
from runner.runner import Runner
from utils.coverage import Location
from utils.mutator import Mutator
from runner.function_coverage_runner import FunctionCoverageRunner
from schedule.power_schedule import PowerSchedule
from utils.object_utils import dump_object, load_object

from utils.seed import Seed


class GreyBoxFuzzer(Fuzzer):

    def __init__(self, seeds: List[str], schedule: PowerSchedule, is_print: bool,
                 output_dir: str = "_result", sample_id: int = 0) -> None:
        """Constructor.
        `seeds` - a list of (input) strings to mutate.
        `schedule` - the power schedule to apply.
        `output_dir` - directory for persisting intermediate state.
        `sample_id` - sample identifier for naming persisted files.
        """
        super().__init__()
        self.is_print = is_print
        self.last_crash_time = self.start_time
        self.population: List[Seed] = []
        self.file_map: Dict = {}
        self.covered_line: Set[Location] = set()
        self.seed_index = 0
        self.crash_map: Dict = dict()
        self.seeds = seeds
        self.mutator = Mutator()
        self.schedule = schedule
        self.output_dir = output_dir
        self.sample_id = sample_id
        self.last_save_time = self.start_time
        self.save_interval_execs = 500
        self.save_interval_secs = 30
        if is_print:
            print("""
┌───────────────────────┬───────────────────────┬───────────────────┬────────────────┬───────────────────┐
│        Run Time       │    Last Uniq Crash    │    Total Execs    │  Uniq Crashes  │   Covered Lines   │
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤""")

    def save_state(self) -> None:
        """Persist population, crashes and evicted seeds to disk."""
        os.makedirs(self.output_dir, exist_ok=True)
        prefix = os.path.join(self.output_dir, f"Sample-{self.sample_id}")

        if self.population:
            dump_object(f"{prefix}_population.pkl", self.population)

        if self.crash_map:
            # Deduplicate: keep only one input per unique crash hash
            deduped: Dict[str, str] = {}
            for inp, h in self.crash_map.items():
                if h not in deduped:
                    deduped[h] = inp
                elif len(inp) < len(deduped[h]):
                    deduped[h] = inp  # keep shorter input for easier reproduction
            dump_object(f"{prefix}_crashes.pkl", deduped)

        if self.schedule.evicted_seeds:
            evicted_path = f"{prefix}_evicted.pkl"
            existing = []
            if os.path.exists(evicted_path):
                try:
                    existing = load_object(evicted_path)
                except Exception:
                    pass
            existing.extend(self.schedule.evicted_seeds)
            dump_object(evicted_path, existing)
            self.schedule.evicted_seeds.clear()

    def resume_state(self) -> bool:
        """Try to restore population and crashes from a previous run."""
        prefix = os.path.join(self.output_dir, f"Sample-{self.sample_id}")
        pop_path = f"{prefix}_population.pkl"
        crash_path = f"{prefix}_crashes.pkl"

        if not os.path.exists(pop_path):
            return False

        try:
            self.population = load_object(pop_path)
            if os.path.exists(crash_path):
                saved_crashes = load_object(crash_path)
                if saved_crashes:
                    first_key = next(iter(saved_crashes.keys()))
                    if len(first_key) == 32 and all(c in '0123456789abcdef' for c in first_key):
                        # Deduped format (hash -> input): convert back to (input -> hash)
                        self.crash_map = {inp: h for h, inp in saved_crashes.items()}
                    else:
                        self.crash_map = saved_crashes
            for seed in self.population:
                self.covered_line |= seed.coverage
            return True
        except Exception:
            return False


    def create_candidate(self) -> str:
        """Returns an input generated by fuzzing a seed in the population"""
        seed = self.schedule.choose(self.population)

        # Stacking: Apply multiple mutations to generate the candidate
        candidate = seed.data
        trials = min(len(candidate), 1 << random.randint(1, 5))
        for i in range(trials):
            candidate = self.mutator.mutate(candidate)
        return candidate

    def fuzz(self) -> str:
        """Returns first each seed once and then generates new inputs"""
        if self.seed_index < len(self.seeds):
            # Still seeding
            self.inp = self.seeds[self.seed_index]
            self.seed_index += 1
        else:
            # Mutating
            self.inp = self.create_candidate()

        return self.inp

    def print_stats(self):
        if not self.is_print:
            return

        def format_seconds(seconds):
            hours = int(seconds) // 3600
            minutes = int(seconds % 3600) // 60
            remaining_seconds = int(seconds) % 60
            return f"{hours:02d}:{minutes:02d}:{remaining_seconds:02d}"

        template = """│{runtime}│{crash_time}│{total_exec}│{uniq_crash}│{covered_line}│
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤"""

        template = template.format(runtime=format_seconds(time.time() - self.start_time).center(23),
                                   crash_time=format_seconds(self.last_crash_time - self.start_time).center(23),
                                   total_exec=str(self.total_execs).center(19),
                                   uniq_crash=str(len(set(self.crash_map.values()))).center(16),
                                   covered_line=str(len(self.covered_line)).center(19))
        print(template)

    def run(self, runner: FunctionCoverageRunner) -> Tuple[Any, str]:  # type: ignore
        """Run function(inp) while tracking coverage.
           If we reach new coverage,
           add inp to population and its coverage to population_coverage
        """
        result, outcome = super().run(runner)
        if len(self.covered_line) != len(runner.all_coverage):
            self.covered_line |= runner.all_coverage
            if outcome == Runner.PASS:
                # We have new coverage
                seed = Seed(self.inp, runner.coverage())
                self.population.append(seed)
        if outcome == Runner.FAIL:
            self.last_crash_time = time.time()
            self.crash_map[self.inp] = result

        if self.total_execs % self.save_interval_execs == 0 or \
           time.time() - self.last_save_time > self.save_interval_secs:
            self.save_state()
            self.last_save_time = time.time()

        return result, outcome
